In [1]:
import numpy as np
import scipy
import sys

In [2]:
a = np.array([[0],
             [1],
             [2],
             [3]])

In [3]:
np.matrix(a)

matrix([[0],
        [1],
        [2],
        [3]])

# Creating sparse matrix

In [4]:
from scipy import sparse

In [5]:
a = np.array([
    [0,0],
    [0,1],
    [3,0]
])

In [6]:
# csr = compressed sparse row matrix
sparse_matrix = sparse.csc_matrix(a)

In [7]:
sparse_matrix

<3x2 sparse matrix of type '<class 'numpy.intc'>'
	with 2 stored elements in Compressed Sparse Column format>

In [8]:
sys.getsizeof(a)

136

In [9]:
sys.getsizeof(sparse_matrix)

48

# Vectorize ordinary functions

In [10]:
def relu(x):
    return np.max([0,x])

In [11]:
np.vectorize(relu)(a)

array([[0, 0],
       [0, 1],
       [3, 0]])

# Calculate Mean, Variance and Standard Deviation

In [12]:
a = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [13]:
np.mean(a),np.var(a),np.std(a)

(5.0, 6.666666666666667, 2.581988897471611)

# Flatten matrix

In [14]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Find rank of matrix

In [15]:
np.linalg.matrix_rank(a)

2

# Find determinant

In [16]:
np.linalg.det(a)

-9.51619735392994e-16

# Find diagonal of matrix

In [17]:
a.diagonal()

array([1, 5, 9])

# Find trace of matrix

Sum of elements along diagonal of matrix

In [18]:
a.trace()

15

# Finding Eigen values and Eigen vectors

In [19]:
eigen_values, eigen_vectors = np.linalg.eig(a)

In [20]:
eigen_values

array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16])

In [21]:
eigen_vectors

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

# Dot product of vectors

In [22]:
a = np.array([1,2,3])
b = np.array([5,5,5])

In [23]:
np.dot(a,b)

30

# Dot product (Matrix Multiplication)

In [24]:
a = np.array([
    [1,2,-1],
    [0,-4,1],
    [3,-7,8]
])

In [25]:
b = np.array([
    [7,-1,-5],
    [7,3,-2],
    [-6,4,3]
])

In [26]:
np.dot(a,b)

array([[ 27,   1, -12],
       [-34,  -8,  11],
       [-76,   8,  23]])

In [27]:
# or
a@b

array([[ 27,   1, -12],
       [-34,  -8,  11],
       [-76,   8,  23]])

In [28]:
# or
np.matmul(a,b)

array([[ 27,   1, -12],
       [-34,  -8,  11],
       [-76,   8,  23]])

# Elementwise multiplication of matrices

In [29]:
np.multiply(a,b)

array([[  7,  -2,   5],
       [  0, -12,  -2],
       [-18, -28,  24]])

# Inverting matrix

In [30]:
np.linalg.inv(a)

array([[ 0.80645161,  0.29032258,  0.06451613],
       [-0.09677419, -0.35483871,  0.03225806],
       [-0.38709677, -0.41935484,  0.12903226]])

# Generating Random Values

In [31]:
np.random.randint(0,10,5)

array([7, 7, 7, 0, 4])

#  Draw three numbers from a normal distribution with mean 0.0 and standard deviation of 1.0

In [32]:
np.random.normal(0.0, 1.0, 3)

array([-0.28039216, -0.27562797, -1.81170103])

# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0

In [33]:
np.random.logistic(0.0, 1.0, 3)

array([ 2.43095011,  1.32946301, -3.38793371])

# Draw three numbers greater than or equal to 1.0 and less than 2.0

In [34]:
np.random.uniform(1.0, 2.0, 3)

array([1.67316955, 1.16189497, 1.04692827])